name: 'Auto Release Draft'
description: 'Drafts a Github release with the changes introduce by a version tag'
outputs:
  release-url: # output will be available to future steps
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
