name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create a release draft for a version tag 
      id: create-release-draft
      uses: ./
    
    - name: Print the URL of the release draft
      run: echo ${{ steps.create-release-draft.outputs.release-url}}
